"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from .errorcodes401 import *
from .errorcodes403 import *
from .errorcodes404 import *
from .errorcodes500 import *
from .errordetail401 import *
from .errordetail403 import *
from .errordetail404 import *
from .errordetail500 import *
from .errorresponse400 import *
from .errorresponse401 import *
from .errorresponse403 import *
from .errorresponse404 import *
from .errorresponse500 import *
from .historicalrateerrorcodes400 import *
from .historicalrateerrordetail400 import *
from .walletapierror import *
from .sdkerror import SDKError
__all__ = ["ErrorCodes401","ErrorCodes403","ErrorCodes404","ErrorCodes500","ErrorDetail401","ErrorDetail403","ErrorDetail404","ErrorDetail500","ErrorResponse400","ErrorResponse401","ErrorResponse403","ErrorResponse404","ErrorResponse500","HistoricalRateErrorCodes400","HistoricalRateErrorDetail400","WalletAPIError","WalletAPIErrorStatus","SDKError"]
