"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ErrorCodes403(str, Enum):
    r"""The detailed error code associated with HTTP status 403.
    * `fx_client_no_access`: The client is authenticated but not authorized.
    """
    FX_CLIENT_NO_ACCESS = 'fx_client_no_access'
