"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ErrorCodes500(str, Enum):
    r"""The detailed error code associated with HTTP status 500.
    * `fx_dependency_error`: Error happens when the service calls its dependencies.
    * `fx_uncategorized_error`: Service errors not categorized.
    """
    FX_DEPENDENCY_ERROR = 'fx_dependency_error'
    FX_UNCATEGORIZED_ERROR = 'fx_uncategorized_error'
