"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class CancellationReason(str, Enum):
    r"""Reason for a conversion cancellation.
      * `user_cancel`: User initiated cancellation.
      * `insufficient_fund`: Cancellation due to insufficient balance in the wallet at the time of conversion execution.
    """
    USER_CANCEL = 'user_cancel'
    INSUFFICIENT_FUND = 'insufficient_fund'
