"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ConversionStatus(str, Enum):
    r"""The status of the conversion."""
    CREATED = 'created'
    PROCESSING = 'processing'
    COMPLETED = 'completed'
    CANCELLED = 'cancelled'
    FAILED = 'failed'
    PENDING_CANCELLATION = 'pending_cancellation'
