"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ErrorCodes404(str, Enum):
    r"""The detailed error code associated with HTTP status 404.
    * `fx_quote_not_found`: The provided quote cannot be found in the service.
    * `fx_fee_configuration_not_found`: The configuration cannot be found for at least one of the fees.
    """
    FX_QUOTE_NOT_FOUND = 'fx_quote_not_found'
    FX_FEE_CONFIGURATION_NOT_FOUND = 'fx_fee_configuration_not_found'
