"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class LockPeriod(str, Enum):
    r"""The duration for which the quote remains valid after creation."""
    FIVE_MINS = '5_mins'
    FIFTEEN_MINS = '15_mins'
    ONE_HOUR = '1_hour'
    FOUR_HOURS = '4_hours'
    EIGHT_HOURS = '8_hours'
    TWENTY_FOUR_HOURS = '24_hours'
