"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class Window(str, Enum):
    r"""Specifies the field by which the results should be grouped."""
    ONE_DAY = '1_day'
    ONE_HOUR = '1_hour'
