"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""


import requests as requests_http
from .utils import utils
from .utils.retries import RetryConfig
from dataclasses import dataclass
from nium_platform.models import shared
from typing import Callable, Dict, Tuple, Union


SERVERS = [
    'https://gatewaysandbox.nium.com/',
]
"""Contains the list of servers available to the SDK"""

@dataclass
class SDKConfiguration:
    client: requests_http.Session
    security: Union[shared.Security,Callable[[], shared.Security]] = None
    server_url: str = ''
    server_idx: int = 0
    language: str = 'python'
    openapi_doc_version: str = '10.27.2023'
    sdk_version: str = '0.3.1'
    gen_version: str = '2.258.2'
    user_agent: str = 'speakeasy-sdk/python 0.3.1 2.258.2 10.27.2023 NIUM-Platform'
    retry_config: RetryConfig = None

    def get_server_details(self) -> Tuple[str, Dict[str, str]]:
        if self.server_url:
            return utils.remove_suffix(self.server_url, '/'), {}
        if self.server_idx is None:
            self.server_idx = 0

        return SERVERS[self.server_idx], {}
